shared: &shared_settings
  identity_map_enabled: true

development:
  <<: *shared_settings
  host: localhost
  database: s3_upload_development

test:
  <<: *shared_settings
  host: localhost
  database: s3_upload_test

# set these environment variables on your prod server
production:
  <<: *shared_settings
  host: localhost
  database: s3_upload_production